version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: gym_erp_db
    restart: always
    environment:
      POSTGRES_USER: gym_admin
      POSTGRES_PASSWORD: gym_password_secret
      POSTGRES_DB: gym_erp_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
